parameters:
#    learning_user.example.class: Learning\UserBundle\Example

services:
#    learning_user.example:
#        class: %learning_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
